java.lang.RuntimeException: Error receiving broadcast Intent { act=com.klinker.android.messaging.UPDATE_HALO flg=0x10 (has extras) } in com.klinker.android.messaging_sliding.slide_over.SlideOverService@420d7728         at android.app.LoadedApk.run(LoadedApk.java:773)         at android.os.Handler.handleCallback(Handler.java:730)         at android.os.Handler.dispatchMessage(Handler.java:92)         at android.os.Looper.loop(Looper.java:137)         at android.app.ActivityThread.main(ActivityThread.java:5151)         at java.lang.reflect.Method.invokeNative(Native Method)         at java.lang.reflect.Method.invoke(Method.java:525)         at com.android.internal.os.ZygoteInit.run(ZygoteInit.java:737)         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)         at dalvik.system.NativeStart.main(Native Method)         Caused by: java.lang.IllegalArgumentException: View not attached to window manager         at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:406)         at android.view.WindowManagerGlobal.updateViewLayout(WindowManagerGlobal.java:295)         at android.view.WindowManagerImpl.updateViewLayout(WindowManagerImpl.java:74)         at com.klinker.android.messaging_sliding.slide_over.SlideOverService.onReceive(SlideOverService.java:652)         at android.app.LoadedApk.run(LoadedApk.java:763)
That is the log for the error that comes up whenever i recieve a new message